version: '3'
services:

  web:
    restart: always
    build: ./angular_frontend/family-project
    ports:
     - "4200:4200"
    depends_on:
        - app

  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always

  app:
    restart: always
    build: ./spring__backend/FamilyTaskCV
    working_dir: /spring__backend/FamilyTaskCV
    volumes:
      - ./spring__backend/FamilyTaskCV:/spring__backend/FamilyTaskCV
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql